### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by manuvarkey** [manuvarkey/GElectrical#1]
### Functionality
- [ ] Associative property/ let through energy calculations.
- [ ] Coordination analysis tools for marking critical points.
- [ ] OLTC controller for power flow (Time series).
- [ ] Powerflow simulation with diversity factors.
- [ ] OLTC controller for power flow.
- [ ] Handling of distributed neutral.
- [ ] Handling of TT & IT earthing systems.

### Reliability
- [ ] Tests for checking calculation correctness with reference.

### New elements
- [ ] Changeover switch
- [ ] Generator (support for 3 phase power flow)
- [ ] Impedance (support for 3 phase power flow)
- [ ] Shunt capacitor (support for 3 phase power flow)
